typedef complex<double>                         complexd;
typedef vector<int>                             vec1i;
typedef vector<vec1i>                           vec2i;
typedef vector<vec2i>                           vec3i;
typedef vector<vec3i>                           vec4i;
typedef vector<vec4i>                           vec5i;
typedef vector<vec5i>                           vec6i;
typedef vector<double>                          vec1d;
typedef vector<vec1d>                           vec2d;
typedef vector<vec2d>                           vec3d;
typedef vector<vec3d>                           vec4d;
typedef vector<vec4d>                           vec5d;
typedef vector<vec5d>                           vec6d;
typedef vector<complexd>                        vec1x;
typedef vector<vec1x>                           vec2x;
typedef vector<vec2x>                           vec3x;
typedef vector<vec3x>                           vec4x;
typedef vector<vec4x>                           vec5x;
typedef vector<vec5x>                           vec6x;

vec1i    vecE1i; 
vec2i    vecE2i;
vec3i    vecE3i;
vec4i    vecE4i;
vec5i    vecE5i;
vec6i    vecE6i;
vec1d    vecE1d;
vec2d    vecE2d;
vec3d    vecE3d;
vec4d    vecE4d;
vec5d    vecE5d;
vec6d    vecE6d;
vec1x    vecE1x;
vec2x    vecE2x;
vec3x    vecE3x;
vec4x    vecE4x;
vec5x    vecE5x;
vec6x    vecE6x;
